CREATE TABLE IF NOT EXISTS example_table
(
     example_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'PK',
     example_name VARCHAR(10)  NOT NULL DEFAULT '' COMMENT 'example_name',
)ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;